#!/bin/zsh

zle -N concat-with-ampersand
zle -N filter-files

# Concat the previous two commands with ampersand, and
# if there is text in the current buffer, concat it too
function concat-with-ampersand {
   local CMD1
   local CMD2
   local newcmd
   history -2 | sed -e 's/^ *//g;s/ *$//g' | cut -f2- -d ' ' | while read acmd; do
      if [[ -z $CMD1 ]]; then
         CMD1=$acmd
      else
         CMD2=$acmd
      fi
   done
   newcmd="$CMD1 && $CMD2"
   integer newbufflen
   echo $newcmd | wc -c | read newbufflen
   if [[ -z $BUFFER ]]; then
      BUFFER="$newcmd"
      CURSOR=$newbufflen
   else
      BUFFER="$newcmd && $BUFFER"
      CURSOR=$(($newbufflen + 3 + $CURSOR))
   fi
}


# Concat all files in the buffer that exist as files, filtering out all else.
# leaves the cursor at the start of the line for command insertion.
function filter-files {
   local b
   local i
   local newout
   b=${${=BUFFER}[2,-1]}
   if [[ ! -z $b ]]
   then
      CURSOR=0
      newout=""
      for i in $b; do
         if [[ -e $i ]]
         then
            newout="$newout $i"
         fi
      done
      BUFFER="$newout"
   fi
}

bindkey '^e' filter-files
bindkey '^u' concat-with-ampersand

