#!/usr/bin/env zsh

autoload -U colors zsh-mime-setup zargs
colors
zsh-mime-setup


# Automatically quote pasted URLs
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# OSX coloring
export CLICOLOR=1
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
