#!/usr/bin/env zsh

autoload -U history-search-end
autoload -U edit-command-line

# Lookup in /etc/termcap or /etc/terminfo else, you can get the right keycode
# by typing ^v and then type the key or key combination you want to use.
# "man zshzle" for the list of available actions
bindkey -v

typeset -g -A key
key[F1]='^[OP'
key[F2]='^[OQ'
key[F3]='^[OR'
key[F4]='^[OS'
key[F5]='^[[15~'
key[F6]='^[[17~'
key[F7]='^[[18~'
key[F8]='^[[19~'
key[F9]='^[[20~'
key[F10]='^[[21~'
key[F11]='^[[22~'
key[F12]='^[[23~'
key[Backspace]='^?'
key[Delete]='^[[3~'
key[Down]='^[[B'
key[End]='^[[F'
key[Home]='^[[H'
key[Left]='^[[D'
key[PageDown]='^[[6~'
key[PageUp]='^[[5~'
key[Right]='^[[C'
key[Up]='^[[A'


zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end  history-search-end
zle -N edit-command-line
zle -N toggle-prompt
zle -N toggle-suspend

[[ -n ${key[Home]}     ]] && bindkey ${key[Home]}     beginning-of-line
[[ -n ${key[End]}      ]] && bindkey ${key[End]}      end-of-line
[[ -n ${key[Insert]}   ]] && bindkey ${key[Insert]}   overwrite-mode
[[ -n ${key[Delete]}   ]] && bindkey ${key[Delete]}   delete-char
[[ -n ${key[Up]}       ]] && bindkey ${key[Up]}       history-beginning-search-backward
[[ -n ${key[Down]}     ]] && bindkey ${key[Down]}     history-beginning-search-forward
[[ -n ${key[Left]}     ]] && bindkey ${key[Left]}     backward-char
[[ -n ${key[Right]}    ]] && bindkey ${key[Right]}    forward-char
[[ -n ${key[PageUp]}   ]] && bindkey ${key[PageUp]}   history-beginning-search-backward-end
[[ -n ${key[PageDown]} ]] && bindkey ${key[PageDown]} history-beginning-search-forward-end

bindkey '^e' edit-command-line
bindkey '^j' push-line
bindkey '^z' toggle-suspend
bindkey '^x' toggle-prompt
bindkey '^r' history-incremental-search-backward

