#!/usr/bin/env zsh

alias lsh='ls -d .*'                       # Show hidden files
alias lsd='ls -d *(/)'                     # Show directories
alias lse='ls -d *(/^F)'                   # Show empty directories
alias lsw='ls -d *(R,W,X.^/)'              # Show world-accessible files
alias lss='ls *(s,S,t)'                    # Show setgid/setuid/sticky flag
alias lsl='ls *(@)'                        # Show symlinks
alias lsx='ls *(*)'                        # Show executables
alias lsdf='ls --group-directories-first'  # Show directories first
alias lsnew='ls -t *(.om[1,10])'           # Show newest files
alias lsold='ls -rt *(.om[1,10])'          # Show oldest files
alias lsbig='ls -S *(.OL[1,10])'           # Show biggest files

which nvim && alias vim='nvim' # since i always use it anyway

alias la='ls -A'
alias lad='la -d *(D/)'                    # Show directories
alias lae='la -d *(D/^F)'                  # Show empty directories
alias law='la -d *(DR,W,X.^D/)'            # Show world-accessible files
alias lal='la -d *(D@)'                    # Show symlinks
alias las='la *(Ds,S,t)'                   # Show setgid/setuid/sticky flag
alias lax='la *(D*)'                       # Show executables
alias ladf='la --group-directories-first'  # Show directories first
alias lanew='la -t *(D.om[1,10])'          # Show newest files
alias laold='la -rt *(D.om[1,10])'         # Show oldest files
alias labig='la -S *(D.OL[1,10])'          # Show biggest files

alias ll='ls -l'
alias llh='ll -d .*'                       # Show hidden files
alias lld='ll -d *(/)'                     # Show directories
alias lle='ll -d *(/^F)'                   # Show empty directories
alias llw='ll -d *(R,W,X.^/)'              # Show world-accessible files
alias lll='ll -d *(@)'                     # Show symlinks
alias lls='ll *(s,S,t)'                    # Show setgid/setuid/sticky flag
alias llx='ll *(*)'                        # Show executables
alias lldf='ll --group-directories-first'  # Show directories first
alias llnew='ll -t *(.om[1,10])'           # Show newest files
alias llold='ll -rt *(.om[1,10])'          # Show oldest files
alias llbig='ll -S *(.OL[1,10])'           # Show biggest files

alias lla='ll -A'
alias llad='lla -d *(D/)'                    # Show directories
alias llae='lla -d *(D/^F)'                  # Show empty directories
alias llaw='lla -d *(DR,W,X.^D/)'            # Show world-accessible files
alias llal='lla -d *(D@)'                    # Show symlinks
alias llas='lla *(Ds,S,t)'                   # Show setgid/setuid/sticky flag
alias llax='lla *(D*)'                       # Show executables
alias lladf='lla --group-directories-first'  # Show directories first
alias llanew='lla -t *(D.om[1,10])'          # Show newest files
alias llaold='lla -rt *(D.om[1,10])'         # Show oldest files
alias llabig='lla -S *(D.OL[1,10])'          # Show biggest files

# git {{{1

alias g='git'
alias ga='g add'
alias gap='g add --patch'
alias gP='g push'
alias gc='g commit'
alias gd='g diff'
alias gp='g pull'
alias gs='g status'
alias gl='g log --oneline'


# du {{{1

alias duh='du -slh'                 # Human-readable
alias dub='du -slb'                 # Bytes
alias duk='du -slk'                 # Kilobytes
alias dum='du -slm'                 # Megabytes
alias dug='du -sl --block-size=1G'  # Gigabytes

