#!/usr/bin/env ruby

scriptname = File.basename $0
counts = Hash.new

ARGF.each_line do  |l|
   k = l.strip
   next if k == ""
   counts[k] ||= 0
   counts[k] += 1
end

ca = counts.to_a.sort do |a,b|
   a[1] <=> b[1]
end
ca.each do |k,v|
   printf("%d: %s\n", v, k)
end


