#!/usr/bin/env ruby
# This script nags the team for status

require 'builder'
require 'thread'
require 'mail'

ENV["CMVC_FAMILY"] ||= "aix@aix@1500"
ENV["CMVC_AUTH_METHOD"] ||= "PW"
ENV["PATH"] += ":/usr/lpp/cmvc/bin"

status_givers = %w{
armandli
catherin
cbowler
ccambly
clord
jasonli
hstong
jinlee
michael
skasapin
wyehia
yanliu 
xingxue
zibi 
}

class Array
  def to_cmvc
    return "()" if self.empty? 
    case self.first.class.to_s
    when "String"
      "(#{self.map { |s| "'#{s.chomp}'"}.join(",")})"
    else
      "(#{self.map { |s| s.to_s}.join(",")})"
    end
  end
end

def email_addresses(users)
   `Report -view Users -where "login in #{users.to_cmvc}" -raw`.each_line do |l|   
      uid,name,su,addr = l.chomp.split("|")
      yield uid.to_sym, name.gsub(/\n/, " "), addr
   end
end
emails = []
email_addresses(status_givers) do |e,n,a|
   emails << a.to_s
end

mail = Mail.new do  
   from "NagBot XL-3000 <cmvc_nag_noreply@ca.ibm.com>"
   to emails
   subject "Nag: Today: Please Update Your RTC Status <nt>"
   body "<no text!>"
end

mail.delivery_method :sendmail
mail.deliver



