#!/usr/bin/env ruby
# Take a random sample of lines out of ARGF, and writes to stdout
# to produce a file of approximately length n, set --probability=#{ruby -e 'puts(n * 1.0 / `wc -l file`)' }

require 'set'
require 'fileutils'
require 'optparse'
include FileUtils

probability = 0.5

opts = OptionParser.new do |opts|
   opts.banner = "Usage: #{File.basename($0)} [--probability=P]"
   opts.on("--probability=P", Float, "Odds of keeping any given line") do |p|
      probability = p
   end
end.parse!

while line = ARGF.gets
   next if rand > probability
   puts line
end
